### ISSUE TITLE
DWCC context aware Navigation/Home page

### ISSUE THREAD

**Issue by charl3sj** [hasirudala/dwcc-web#8]
On login, user should be taken to homepage. Homepage contains navigation links to main functions:
1. Record Incoming/Outgoing Waste data
2. Record Expenses
3. Manage staff/assets
4. Record attendance
etc. etc.

# BUT
Before showing the menu, User should be prompted to select DWCC against which they want to enter data. 

It should be possible to easily change DWCC context (via navigation item or some such).

##### TEST CASES - 
- Select DWCC page - 
      1. After log in this window should pop up to select the DWCC. 
      2. Change the Ward within Region 
      3. Change the ward outside the region
      4. Logout from the portal and again login it should ask for the selection of DWCC
- Home Page-
      1. After selecting the DWCC, the Home page should display with the four options. (Incoming/Outgoing 
          Waste, Expenses, Staff/assets and Attendance)
      2. If Logout from the system and again login, it should again display the Home page. - **_Fail_**
          Current Behaviour - If user logout from data entry page and again login it comes to data entry page not 
          HOME PAGE.

**Comment by garimadosar5** [comment]
QA Notes - 
1. When I log in as Admin/Staff, on the landing page it asks me to choose the DWCC from Bangalore region. But we will have other regions as well. There are other regions in the system but it is showing only "Bangalore". **_DONE_**
![Screen Shot 2019-12-03 at 3.55.48 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/584420fb-e41e-4146-b343-61299e2c3256)

2. If admin wants to go to Admin page then it should not ask to select the region and DWCC. - **_DONE_**

**Comment by charl3sj** [comment]
1. That is because there are no DWCCs linked to the other Regions/Wards. This is a "Select DWCC" page... not "Select Region" nor "Select Ward"... so they won't show up.
2. True. Will have to rethink this.

**Comment by garimadosar5** [comment]
QA Notes - 
If Logout from the system and again login, it should again display the Home page.
Current Behaviour - If user logout from data entry page and again login it comes to data entry page not
HOME PAGE. (Not sure if that needs to be fixed as of now)

**Comment by charl3sj** [comment]
No, it doesn't have to display the home page. It should open whatever page you signed off from... or more correctly, whatever is the current URL. This is a feature. Not a bug.
